Fix of NTL::zz_p wrapper

diff --git a/trunk/linbox/configure.in b/trunk/linbox/configure.in
--- a/trunk/linbox/configure.in
+++ b/trunk/linbox/configure.in
@@ -28,7 +28,17 @@ exit 1
 ])
 
 LB_CHECK_NTL
-LB_CHECK_GIVARO
+LB_CHECK_GIVARO(,,[
+echo '*******************************************************************************'
+echo ' ERROR: GIVARO not found!'
+echo
+echo ' GIVARO version 3.0 or greater is required for this library to compile. Please'
+echo ' make sure GIVARO is installed and specify its location with the option'
+echo ' --with-givaro-prefix=<prefix> when running configure.'
+echo '*******************************************************************************'
+exit 1
+])
+
 LB_CHECK_SACLIB
 
 AC_CHECK_PROG(DOCPLUSPLUS_SUBDIRS,doc++,"html")
@@ -61,6 +71,7 @@ doc/Makefile
 doc/html/Makefile
 doc/tex/Makefile
 examples/Makefile
+examples/beginners/Makefile
 examples/data/Makefile
 linbox/Makefile
 linbox/algorithms/Makefile
