2005-11-17 Pascal Giorgi: 	* configure.in: remove ATLAS checking and replace with BLAS checking 	* linbox-config.in:  remove ATLAS libs and replace with BLAS libs

diff --git a/trunk/linbox/configure.in b/trunk/linbox/configure.in
--- a/trunk/linbox/configure.in
+++ b/trunk/linbox/configure.in
@@ -112,7 +112,18 @@ LB_CHECK_GIVARO
 LB_CHECK_SACLIB
 LB_CHECK_LIDIA
 LB_CHECK_MAPLE
-LB_CHECK_ATLAS
+#LB_CHECK_ATLAS
+LB_CHECK_BLAS(,,[
+echo ''
+echo '*******************************************************************************'
+echo ' ERROR: BLAS not found!'
+echo
+echo ' BLAS routines are required for this library to compile. Please'
+echo ' make sure BLAS are installed and specify its location with the option'
+echo ' --with-blas=<lib> when running configure.'
+echo '*******************************************************************************'
+exit 1
+])
 LB_CHECK_EXPAT
 
 LB_OPT
@@ -128,6 +139,7 @@ linbox-config
 examples/Makefile
 examples/fields/Makefile
 examples/Readme-make
+examples/solver/Makefile
 gmp++/Makefile
 doc/Makefile
 linbox/Makefile
